name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"   # jalan tiap jam 00:00 UTC (07:00 WIB)
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          echo "Update: $(date)" >> update.log

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto commit"
          git push
